"""Update DB schema

Revision ID: 3357ecf8449f
Revises: 5afa5287a902
Create Date: 2025-06-21 23:22:56.630995

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3357ecf8449f"
down_revision: Union[str, Sequence[str], None] = "5afa5287a902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("github_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "github_id")
    # ### end Alembic commands ###
