"""Update DB schema

Revision ID: b404fa5bb2a5
Revises: fd7e51b8da81
Create Date: 2025-06-22 14:10:33.748092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b404fa5bb2a5"
down_revision: Union[str, Sequence[str], None] = "fd7e51b8da81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tutorials", sa.Column("user_id", sa.String(), nullable=False))
    op.add_column("tutorials", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("tutorials", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.drop_column("tutorials", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tutorials", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("tutorials", "updated_at")
    op.drop_column("tutorials", "created_at")
    op.drop_column("tutorials", "user_id")
    # ### end Alembic commands ###
