"""Update DB schema

Revision ID: fd7e51b8da81
Revises: db9881333638
Create Date: 2025-06-22 11:45:12.379821

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd7e51b8da81"
down_revision: Union[str, Sequence[str], None] = "db9881333638"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tutorials", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tutorials", "status")
    # ### end Alembic commands ###
